import { useState } from "react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Play, Download, Share, Image, Code, Eye, Gamepad2, Brain } from "lucide-react";
import { useGame } from "@/contexts/GameContext";
import { AgentFlowPanel } from "./AgentFlowPanel";

export function GamePanel() {
  const { gameState } = useGame();
  const [activeTab, setActiveTab] = useState("preview");

  // Empty state when no game is generated yet
  const emptyState = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Memory Card Game</title>
    <style>
        body {
            font-family: 'Rajdhani', sans-serif;
            background: linear-gradient(135deg, #0f172a, #1e293b);
            color: #e2e8f0;
            margin: 0;
            padding: 20px;
            min-height: 100vh;
        }
        
        .game-container {
            max-width: 600px;
            margin: 0 auto;
            text-align: center;
        }
        
        .game-title {
            font-size: 2.5rem;
            color: #00ffff;
            text-shadow: 0 0 20px #00ffff;
            margin-bottom: 30px;
        }
        
        .game-board {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 15px;
            margin: 30px 0;
        }
        
        .card {
            aspect-ratio: 1;
            background: linear-gradient(135deg, #1e293b, #334155);
            border: 2px solid #00ffff;
            border-radius: 10px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 2rem;
            cursor: pointer;
            transition: all 0.3s ease;
            position: relative;
            overflow: hidden;
        }
        
        .card:hover {
            transform: scale(1.05);
            box-shadow: 0 0 20px #00ffff;
        }
        
        .card.flipped {
            background: linear-gradient(135deg, #8b5cf6, #a855f7);
            border-color: #8b5cf6;
        }
        
        .card.matched {
            background: linear-gradient(135deg, #10b981, #059669);
            border-color: #10b981;
        }
        
        .stats {
            display: flex;
            justify-content: space-around;
            margin: 20px 0;
        }
        
        .stat {
            text-align: center;
        }
        
        .stat-value {
            font-size: 2rem;
            font-weight: bold;
            color: #00ffff;
        }
        
        .stat-label {
            font-size: 0.9rem;
            color: #64748b;
        }
    </style>
</head>
<body>
    <div class="game-container">
        <h1 class="game-title">MEMORY MATRIX</h1>
        
        <div class="stats">
            <div class="stat">
                <div class="stat-value" id="moves">0</div>
                <div class="stat-label">MOVES</div>
            </div>
            <div class="stat">
                <div class="stat-value" id="matches">0</div>
                <div class="stat-label">MATCHES</div>
            </div>
            <div class="stat">
                <div class="stat-value" id="timer">00:00</div>
                <div class="stat-label">TIME</div>
            </div>
        </div>
        
        <div class="game-board" id="gameBoard">
            <!-- Cards will be generated by JavaScript -->
        </div>
        
        <button onclick="resetGame()" style="
            background: linear-gradient(135deg, #00ffff, #8b5cf6);
            border: none;
            padding: 15px 30px;
            border-radius: 10px;
            color: #0f172a;
            font-weight: bold;
            font-size: 1.1rem;
            cursor: pointer;
            margin-top: 20px;
        ">RESET GAME</button>
    </div>
    
    <script>
        // Game logic will be implemented here
        const symbols = ['🎮', '🎯', '🎲', '🎪', '🎨', '🎭', '🎸', '🎬'];
        const cards = [...symbols, ...symbols];
        let flippedCards = [];
        let moves = 0;
        let matches = 0;
        let startTime = Date.now();
        
        function shuffle(array) {
            for (let i = array.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                [array[i], array[j]] = [array[j], array[i]];
            }
            return array;
        }
        
        function createBoard() {
            const gameBoard = document.getElementById('gameBoard');
            gameBoard.innerHTML = '';
            shuffle(cards);
            
            cards.forEach((symbol, index) => {
                const card = document.createElement('div');
                card.className = 'card';
                card.dataset.symbol = symbol;
                card.dataset.index = index;
                card.innerHTML = '?';
                card.addEventListener('click', flipCard);
                gameBoard.appendChild(card);
            });
        }
        
        function flipCard(e) {
            const card = e.target;
            if (card.classList.contains('flipped') || card.classList.contains('matched') || flippedCards.length === 2) {
                return;
            }
            
            card.classList.add('flipped');
            card.innerHTML = card.dataset.symbol;
            flippedCards.push(card);
            
            if (flippedCards.length === 2) {
                moves++;
                document.getElementById('moves').textContent = moves;
                checkMatch();
            }
        }
        
        function checkMatch() {
            const [card1, card2] = flippedCards;
            
            setTimeout(() => {
                if (card1.dataset.symbol === card2.dataset.symbol) {
                    card1.classList.add('matched');
                    card2.classList.add('matched');
                    matches++;
                    document.getElementById('matches').textContent = matches;
                    
                    if (matches === symbols.length) {
                        alert('Congratulations! You won!');
                    }
                } else {
                    card1.classList.remove('flipped');
                    card2.classList.remove('flipped');
                    card1.innerHTML = '?';
                    card2.innerHTML = '?';
                }
                flippedCards = [];
            }, 1000);
        }
        
        function resetGame() {
            moves = 0;
            matches = 0;
            flippedCards = [];
            startTime = Date.now();
            document.getElementById('moves').textContent = '0';
            document.getElementById('matches').textContent = '0';
            document.getElementById('timer').textContent = '00:00';
            createBoard();
        }
        
        // Timer
        setInterval(() => {
            const elapsed = Math.floor((Date.now() - startTime) / 1000);
            const minutes = Math.floor(elapsed / 60).toString().padStart(2, '0');
            const seconds = (elapsed % 60).toString().padStart(2, '0');
            document.getElementById('timer').textContent = minutes + ':' + seconds;
        }, 1000);
        
        // Initialize game
        createBoard();
    </script>
</body>
</html>`;

  // Helper function to format bytes
  const formatBytes = (bytes: number): string => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  // Helper function to get category display name
  const getCategoryDisplayName = (category: string): string => {
    return category.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  };

  return (
    <div className="h-full flex flex-col">
      <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col">
        <TabsList className="grid w-full grid-cols-4 bg-muted/20 backdrop-blur">
          <TabsTrigger 
            value="preview" 
            className="data-[state=active]:bg-primary/20 data-[state=active]:text-primary data-[state=active]:shadow-[var(--shadow-neon)]"
          >
            <Eye className="w-4 h-4 mr-2" />
            Preview
          </TabsTrigger>
          <TabsTrigger 
            value="agents"
            className="data-[state=active]:bg-blue-500/20 data-[state=active]:text-blue-400 data-[state=active]:shadow-[0_0_10px_rgba(59,130,246,0.5)]"
          >
            <Brain className="w-4 h-4 mr-2" />
            Agents
          </TabsTrigger>
          <TabsTrigger 
            value="assets"
            className="data-[state=active]:bg-secondary/20 data-[state=active]:text-secondary data-[state=active]:shadow-[var(--shadow-purple)]"
          >
            <Image className="w-4 h-4 mr-2" />
            Assets
          </TabsTrigger>
          <TabsTrigger 
            value="code"
            className="data-[state=active]:bg-accent/20 data-[state=active]:text-accent data-[state=active]:shadow-[var(--shadow-pink)]"
          >
            <Code className="w-4 h-4 mr-2" />
            Code
          </TabsTrigger>
        </TabsList>

        <TabsContent value="preview" className="flex-1 p-4">
          <Card className="h-full bg-background/50 border-primary/30 backdrop-blur cyber-grid">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <CardTitle className="text-primary font-orbitron">Game Preview</CardTitle>
                <div className="flex space-x-2">
                  <Button size="sm" variant="outline" className="border-primary/30 hover:border-primary/50">
                    <Play className="w-4 h-4 mr-2" />
                    Run
                  </Button>
                  <Button size="sm" variant="outline" className="border-secondary/30 hover:border-secondary/50">
                    <Share className="w-4 h-4 mr-2" />
                    Share
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent className="h-[calc(100%-80px)]">
              <div className="w-full h-full bg-gradient-to-br from-background to-muted/20 rounded-lg border border-border/50 overflow-hidden">
                {gameState.isGenerating && gameState.operationType === 'game_creation' ? (
                  <div className="flex items-center justify-center h-full">
                    <div className="text-center space-y-4">
                      <div className="w-16 h-16 mx-auto bg-gradient-to-r from-primary/20 to-secondary/20 rounded-lg flex items-center justify-center">
                        <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin"></div>
                      </div>
                      <div>
                        <h3 className="font-orbitron font-bold text-lg text-primary mb-2">
                          {gameState.status === 'thinking' ? 'Planning Your Game' : 'Generating Code'}
                        </h3>
                        <p className="text-sm text-muted-foreground max-w-xs">
                          Maya is creating your game. This may take a minute...
                        </p>
                      </div>
                    </div>
                  </div>
                ) : gameState.code?.html ? (
                  <iframe
                    srcDoc={(() => {
                      // Combine HTML, CSS, and JS into a complete document
                      const html = gameState.code.html;
                      const css = gameState.code.css || '';
                      const js = gameState.code.js || '';
                      
                      console.log('Preview HTML:', html?.slice(0, 100));
                      console.log('Preview CSS:', css?.slice(0, 100));  
                      console.log('Preview JS:', js?.slice(0, 100));
                      
                      // If HTML already contains <style> and <script> tags, use as-is
                      if (html.includes('<style>') && html.includes('<script>')) {
                        console.log('Using complete HTML as-is');
                        return html;
                      }
                      
                      // Otherwise, inject CSS and JS into the HTML
                      let completeHTML = html;
                      
                      // Add CSS if provided and not already present
                      if (css && !html.includes('<style>')) {
                        completeHTML = completeHTML.replace(
                          '</head>',
                          `<style>${css}</style></head>`
                        );
                        console.log('Added CSS to HTML');
                      }
                      
                      // Add JS if provided and not already present
                      if (js && !html.includes('<script>')) {
                        completeHTML = completeHTML.replace(
                          '</body>',
                          `<script>${js}</script></body>`
                        );
                        console.log('Added JS to HTML');
                      }
                      
                      console.log('Final HTML length:', completeHTML.length);
                      return completeHTML;
                    })()}
                    className="w-full h-full border-0"
                    title="Game Preview"
                    sandbox="allow-scripts allow-same-origin allow-forms allow-popups"
                    style={{ backgroundColor: '#0f172a' }}
                  />
                ) : gameState.status === 'error' ? (
                  <div className="flex items-center justify-center h-full">
                    <div className="text-center space-y-4">
                      <div className="w-16 h-16 mx-auto bg-gradient-to-r from-destructive/20 to-destructive/30 rounded-lg flex items-center justify-center">
                        <span className="text-2xl">❌</span>
                      </div>
                      <div>
                        <h3 className="font-orbitron font-bold text-lg text-destructive mb-2">
                          Generation Failed
                        </h3>
                        <p className="text-sm text-muted-foreground max-w-xs">
                          {gameState.error || 'Something went wrong. Please try again.'}
                        </p>
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="flex items-center justify-center h-full">
                    <div className="text-center space-y-4">
                      <div className="w-16 h-16 mx-auto bg-gradient-to-r from-primary/20 to-secondary/20 rounded-lg flex items-center justify-center">
                        <Gamepad2 className="w-8 h-8 text-primary" />
                      </div>
                      <div>
                        <h3 className="font-orbitron font-bold text-lg text-primary mb-2">
                          Ready to Create
                        </h3>
                        <p className="text-sm text-muted-foreground max-w-xs">
                          Your game will appear here once Maya generates the code. 
                          Start by describing your game idea in the chat.
                        </p>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="agents" className="flex-1">
          <AgentFlowPanel />
        </TabsContent>

        <TabsContent value="assets" className="flex-1 p-4">
          <Card className="h-full bg-background/50 border-secondary/30 backdrop-blur">
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle className="text-secondary font-orbitron">Game Assets</CardTitle>
                <div className="flex items-center space-x-2">
                  {gameState.assets.isGenerating && (
                    <div className="flex items-center space-x-2 text-xs text-secondary">
                      <div className="w-2 h-2 bg-secondary rounded-full animate-pulse"></div>
                      <span>Generating...</span>
                    </div>
                  )}
                  {gameState.assets.progress.total_requested > 0 && (
                    <div className="text-xs text-muted-foreground">
                      {gameState.assets.progress.total_generated}/{gameState.assets.progress.total_requested} assets
                    </div>
                  )}
                </div>
              </div>
              {gameState.assets.progress.current_step !== 'idle' && (
                <div className="text-xs text-muted-foreground mt-2">
                  {gameState.assets.progress.current_step}
                </div>
              )}
            </CardHeader>
            <CardContent className="space-y-4">
              {gameState.assets.assets.length > 0 ? (
                <>
                  {/* Asset Gallery Grid */}
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    {gameState.assets.assets.map((asset, index) => (
                      <div
                        key={index}
                        className="bg-muted/20 rounded-lg border border-secondary/20 hover:border-secondary/40 transition-all duration-300 overflow-hidden group"
                      >
                        {/* Asset Preview */}
                        <div className="aspect-square bg-gradient-to-br from-secondary/10 to-accent/10 relative overflow-hidden">
                          {asset.preview_url ? (
                            <img
                              src={asset.preview_url}
                              alt={getCategoryDisplayName(asset.category)}
                              className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
                              onError={(e) => {
                                // Fallback to icon if image fails to load
                                const target = e.target as HTMLImageElement;
                                target.style.display = 'none';
                                target.nextElementSibling?.classList.remove('hidden');
                              }}
                            />
                          ) : null}
                          {/* Fallback icon */}
                          <div className="absolute inset-0 flex items-center justify-center text-secondary/50">
                            <Image className="w-12 h-12" />
                          </div>
                          
                          {/* Status overlay */}
                          <div className="absolute top-2 right-2">
                            <div className={`px-2 py-1 rounded-full text-xs font-medium ${
                              asset.status === 'completed' 
                                ? 'bg-green-500/20 text-green-400 border border-green-500/30'
                                : asset.status === 'generating'
                                ? 'bg-secondary/20 text-secondary border border-secondary/30'
                                : 'bg-red-500/20 text-red-400 border border-red-500/30'
                            }`}>
                              {asset.status === 'completed' && '✓'}
                              {asset.status === 'generating' && '⏳'}
                              {asset.status === 'error' && '❌'}
                            </div>
                          </div>
                        </div>
                        
                        {/* Asset Info */}
                        <div className="p-3 space-y-2">
                          <div>
                            <h3 className="text-sm font-medium text-foreground">
                              {getCategoryDisplayName(asset.category)}
                            </h3>
                            <p className="text-xs text-muted-foreground">
                              PNG • {formatBytes(asset.size_bytes)}
                            </p>
                          </div>
                          
                          {/* Action Buttons */}
                          <div className="flex space-x-2">
                            <Button 
                              size="sm" 
                              variant="outline" 
                              className="border-secondary/30 hover:border-secondary/50 flex-1"
                              onClick={() => {
                                if (asset.preview_url) {
                                  window.open(asset.preview_url, '_blank');
                                }
                              }}
                            >
                              <Eye className="w-3 h-3 mr-1" />
                              View
                            </Button>
                            <Button 
                              size="sm" 
                              variant="outline" 
                              className="border-secondary/30 hover:border-secondary/50"
                              onClick={() => {
                                if (asset.preview_url) {
                                  const link = document.createElement('a');
                                  link.href = asset.preview_url;
                                  link.download = asset.filename;
                                  link.click();
                                }
                              }}
                            >
                              <Download className="w-3 h-3" />
                            </Button>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                  
                  {/* Asset Generation Summary */}
                  {gameState.assets.progress.total_requested > 0 && (
                    <div className="mt-6 p-4 bg-muted/10 rounded-lg border border-secondary/20">
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium">Generation Progress</span>
                        <span className="text-xs text-muted-foreground">
                          {gameState.assets.progress.total_generated}/{gameState.assets.progress.total_requested} completed
                        </span>
                      </div>
                      <div className="w-full bg-muted/20 rounded-full h-2">
                        <div 
                          className="bg-gradient-to-r from-secondary to-accent h-2 rounded-full transition-all duration-300"
                          style={{ 
                            width: `${(gameState.assets.progress.total_generated / gameState.assets.progress.total_requested) * 100}%` 
                          }}
                        />
                      </div>
                    </div>
                  )}
                </>
              ) : gameState.assets.isGenerating ? (
                <div className="flex items-center justify-center h-40">
                  <div className="text-center space-y-4">
                    <div className="w-16 h-16 mx-auto bg-gradient-to-r from-secondary/20 to-accent/20 rounded-lg flex items-center justify-center">
                      <div className="w-8 h-8 border-2 border-secondary border-t-transparent rounded-full animate-spin"></div>
                    </div>
                    <div>
                      <h3 className="font-orbitron font-bold text-lg text-secondary mb-2">
                        Generating Assets
                      </h3>
                      <p className="text-sm text-muted-foreground max-w-xs">
                        Maya is creating visual assets for your game. This may take a few moments.
                      </p>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="flex items-center justify-center h-40">
                  <div className="text-center space-y-4">
                    <div className="w-16 h-16 mx-auto bg-gradient-to-r from-secondary/20 to-accent/20 rounded-lg flex items-center justify-center">
                      <Image className="w-8 h-8 text-secondary" />
                    </div>
                    <div>
                      <h3 className="font-orbitron font-bold text-lg text-secondary mb-2">
                        No assets generated yet
                      </h3>
                      <p className="text-sm text-muted-foreground max-w-xs">
                        Assets will appear here when you create a game with graphics. 
                        Try asking Maya to "create a game with visual assets".
                      </p>
                    </div>
                  </div>
                </div>
              )}
              
              {gameState.assets.error && (
                <div className="mt-4 p-3 bg-red-500/10 border border-red-500/20 rounded-lg">
                  <div className="flex items-center space-x-2">
                    <span className="text-red-400 text-sm">⚠️</span>
                    <span className="text-red-400 text-sm">{gameState.assets.error}</span>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="code" className="flex-1 p-4">
          <Card className="h-full bg-background/50 border-accent/30 backdrop-blur">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <CardTitle className="text-accent font-orbitron">Game Code</CardTitle>
                <div className="flex space-x-2">
                  <Button size="sm" variant="outline" className="border-accent/30 hover:border-accent/50">
                    <Download className="w-4 h-4 mr-2" />
                    Download
                  </Button>
                  <Button size="sm" variant="outline" className="border-accent/30 hover:border-accent/50">
                    <Share className="w-4 h-4 mr-2" />
                    Export
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent className="h-[calc(100%-80px)]">
              <div className="h-full bg-muted/10 rounded-lg border border-accent/20 relative">
                {gameState.codeStream.isStreaming && gameState.codeStream.content ? (
                  <div className="absolute inset-0 overflow-auto p-0">
                    <div className="p-4 space-y-2">
                      <div className="flex items-center gap-2 text-xs text-accent border-b border-accent/20 pb-2">
                        <div className="w-2 h-2 bg-accent rounded-full animate-pulse"></div>
                        <span className="font-medium">Streaming Code - {gameState.codeStream.currentType.toUpperCase()}</span>
                      </div>
                      <pre className="text-xs font-mono text-foreground/90 whitespace-pre-wrap">
                        <code>{gameState.codeStream.content}</code>
                      </pre>
                    </div>
                  </div>
                ) : (gameState.isGenerating && gameState.operationType === 'game_creation') ? (
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="text-center space-y-3">
                      <div className="w-12 h-12 mx-auto border-2 border-accent border-t-transparent rounded-full animate-spin"></div>
                      <div>
                        <h4 className="font-orbitron font-bold text-accent mb-1">
                          Generating Code
                        </h4>
                        <p className="text-xs text-muted-foreground">
                          Creating your game code...
                        </p>
                      </div>
                    </div>
                  </div>
                ) : gameState.code?.html ? (
                  <div className="absolute inset-0 overflow-auto p-0">
                    <pre className="p-4 m-0 text-xs font-mono text-foreground/90 whitespace-pre-wrap">
                    {(() => {
                      // Show the complete combined HTML code
                      const html = gameState.code.html;
                      const css = gameState.code.css || '';
                      const js = gameState.code.js || '';
                      
                      // If HTML already contains <style> and <script> tags, use as-is
                      if (html.includes('<style>') && html.includes('<script>')) {
                        return html;
                      }
                      
                      // Otherwise, combine for display
                      let completeHTML = html;
                      
                      if (css && !html.includes('<style>')) {
                        completeHTML = completeHTML.replace(
                          '</head>',
                          `<style>${css}</style></head>`
                        );
                      }
                      
                      if (js && !html.includes('<script>')) {
                        completeHTML = completeHTML.replace(
                          '</body>',
                          `<script>${js}</script></body>`
                        );
                      }
                      
                      return completeHTML;
                    })()}
                    </pre>
                  </div>
                ) : gameState.status === 'error' ? (
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="text-center space-y-3">
                      <span className="text-4xl">💥</span>
                      <div>
                        <h4 className="font-orbitron font-bold text-destructive mb-1">
                          Code Generation Failed
                        </h4>
                        <p className="text-xs text-muted-foreground">
                          {gameState.error || 'Unable to generate code'}
                        </p>
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="text-center space-y-3">
                      <Code className="w-12 h-12 mx-auto text-accent/50" />
                      <div>
                        <h4 className="font-orbitron font-bold text-accent mb-1">
                          No Code Yet
                        </h4>
                        <p className="text-xs text-muted-foreground">
                          Game code will appear here after generation
                        </p>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}